const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SIGIN_IN_START: 'GOOGLE_SIGIN_IN_START',
  EMAIL_SIGIN_IN_START: 'EMAIL_SIGIN_IN_START',
  SIGIN_IN_SUCCESS: 'SIGIN_IN_SUCCESS',
  SIGIN_IN_FAILURE: 'SIGIN_IN_FAILURE',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_SUCCESS',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
};

export default UserActionTypes;
